// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpmedOpzB1261tjqnI6X8FJ2VurX9LPo',
    appId: '1:440239930081:web:22b3cdbc7a50c56d3655a0',
    messagingSenderId: '440239930081',
    projectId: 'gendersocialapp',
    authDomain: 'gendersocialapp.firebaseapp.com',
    storageBucket: 'gendersocialapp.firebasestorage.app',
    measurementId: 'G-MLPZ45E9EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoH48SUH8FSoicOSOAIl3UlcOqko5n6xk',
    appId: '1:440239930081:android:499771be9c9d2d683655a0',
    messagingSenderId: '440239930081',
    projectId: 'gendersocialapp',
    storageBucket: 'gendersocialapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCospd5-5y_p73KShbtdPaonx4aI1vSCNg',
    appId: '1:440239930081:ios:6d9a186dc467f5e43655a0',
    messagingSenderId: '440239930081',
    projectId: 'gendersocialapp',
    storageBucket: 'gendersocialapp.firebasestorage.app',
    iosBundleId: 'com.example.kam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCospd5-5y_p73KShbtdPaonx4aI1vSCNg',
    appId: '1:440239930081:ios:6d9a186dc467f5e43655a0',
    messagingSenderId: '440239930081',
    projectId: 'gendersocialapp',
    storageBucket: 'gendersocialapp.firebasestorage.app',
    iosBundleId: 'com.example.kam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPpmedOpzB1261tjqnI6X8FJ2VurX9LPo',
    appId: '1:440239930081:web:b25ecc9938f1dd253655a0',
    messagingSenderId: '440239930081',
    projectId: 'gendersocialapp',
    authDomain: 'gendersocialapp.firebaseapp.com',
    storageBucket: 'gendersocialapp.firebasestorage.app',
    measurementId: 'G-44396X3FGE',
  );
}
